- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: test logged in users
      command: w
      register: command_output
      - debug:
        var: command_output.stdout_lines
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
