- hosts: all
  gather_facts: yes
  tasks:
    - name: Upgrade all packages
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: test getting IP
      debug:
        command: w
