- hosts: all
  gather_facts: yes
  tasks:
    - name: Upgrade all packages
      apt:
        name: '*'
        state: latest
        security: yes
    - name: test getting IP
      debug:
        command: w
