---
- name: Install AT Job
  hosts: all
  tasks:
  - name: at command needs to be installed
    apt:
      name: at
      state: present
    become: yes
  - name: Schedule a command to execute in 20 minutes as root
    ansible.posix.at:
      command: ls -d / >/dev/null
      count: 20
      units: minutes
    become: yes
  - name: Using Zabbix collection
  hosts: localhost
    collections:
      - community.zabbix

    roles:
      - role: zabbix_agent
        zabbix_agent_server: zabbix.example.com
